Update plugins.json
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #163
Opened 2022-07-02 15:07 UTC by MayowaAk

2022-07-03 02:35 UTC, taooceros commented
The website is not available?

2022-07-04 15:39 UTC, MayowaAk reviewed
Fixed the mistyped url so the site should load now

2022-07-13 07:56 UTC, taooceros requested changes

2022-07-13 07:56 UTC, taooceros commented on plugins.json
> +        "IcoPath": "icon.png",
```suggestion
        "IcoPath": "[icon.png](https://cdn.jsdelivr.net/gh/MayowaAk/Flow.Launcher.Plugin.AnimeSearch@master/AnimeSearch/Flow.Launcher.Plugin.AnimeSearch/MyAnimeList_Logo.png)",
```

2022-08-03 23:39 UTC, Garulf commented
JSON validator test is failing due to an extra comma.

2022-08-06 10:58 UTC, jjw24 requested changes
Hi @DiekoMA how's it going?

I tested your plugin but all I got was a pop up saying 'Test' when I search. Could you please update it so it's not the test release.

2022-08-06 10:59 UTC, jjw24 commented on plugins.json
> +        "IcoPath": "https://cdn.jsdelivr.net/gh/MayowaAk/Flow.Launcher.Plugin.AnimeSearch@master/AnimeSearch/Flow.Launcher.Plugin.AnimeSearch/MyAnimeList_Logo.png",
```suggestion
        "IcoPath": "https://cdn.jsdelivr.net/gh/MayowaAk/Flow.Launcher.Plugin.AnimeSearch@master/AnimeSearch/Flow.Launcher.Plugin.AnimeSearch/MyAnimeList_Logo.png"
```

2022-08-25 13:14 UTC, closed without merging