Add plugin "Audio Device Selector"
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #195
Opened 2022-12-17 09:31 UTC by attilakapostyak

2022-12-19 22:33 UTC, Garulf requested changes
Looks great! 

![image](https://user-images.githubusercontent.com/535299/208539666-8e55ad44-1fae-47dd-9c09-667f6d6e635c.png)

2022-12-19 22:33 UTC, Garulf commented on plugins.json
> +        "Description": "Easy change your playback device",
```suggestion
        "Description": "Easily change your playback device",
```

2022-12-19 22:33 UTC, Garulf approved these changes

2022-12-19 22:38 UTC, merged

2022-12-20 06:00 UTC, attilakapostyak commented
> Looks great!
> 
> ![image](https://user-images.githubusercontent.com/535299/208539666-8e55ad44-1fae-47dd-9c09-667f6d6e635c.png)

Thanks.