Update plugins.json
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #216
Opened 2023-03-07 16:05 UTC by DeepVoyager253

I made a Youtube downloader plugin, that allows you to type in: -yt URL and will let you choose between downloading and mp3 or an mp4 of the video. if there are any issues that prevent my plugin from getting in, i would like to know how to correct them as i am dedicated to make this project work. Please keep in mind, that it is still in pretty early development.

i.e. I am pretty new to flow launcher plugin development, and if i have any problems with the workflow or plugin.json i would like you to tell me so i can fix it.

2023-03-07 23:42 UTC, Garulf requested changes

2023-03-07 23:42 UTC, Garulf commented on plugins.json
> +    "Website": "n/a",
```suggestion
    "Website": "https://github.com/DeepVoyager253/FlowLauncherYTDownload",
```

Perfectly acceptable to use the GitHub page here.

2023-03-08 00:37 UTC, Garulf requested changes

2023-03-08 00:37 UTC, Garulf commented on plugins.json
> +    "UrlSouceCode": "https://github.com/DeepVoyager253/FlowLauncherYTDownload"
```suggestion
    "UrlSouceCode": "https://github.com/DeepVoyager253/FlowLauncherYTDownload",
```

Looks like a missing `,`

2023-03-08 14:45 UTC, DeepVoyager111 commented
After you've fixed it, can you re-check it?

2023-03-08 17:02 UTC, Garulf commented on plugins.json
> +    "Version": "1.0.0-alpha",
```suggestion
    "Version": "1.0.0-beta",
```

2023-03-08 21:02 UTC, Garulf commented on plugins.json
> +    "Version": "1.0.0-beta",
```suggestion
    "Version": "1.0.0-alpha",
```

2023-03-08 21:34 UTC, Garulf commented on plugins.json
> +    "Version": "v1.0.0-beta",
```suggestion
    "Version": "vv1.0.0-beta",
```

2023-03-09 16:51 UTC, Garulf commented on plugins.json
> +    "UrlDownload": "https://github.com/DeepVoyager253/FlowLauncherYTDownload/archive/refs/heads/main.zip"
```suggestion
    "UrlDownload": "https://github.com/DeepVoyager253/FlowLauncherYTDownload/releases/download/v1.0.0-beta/Flow.Launcher.Plugin.YTDownloader.zip"
```

2023-03-09 16:57 UTC, DeepVoyager253 reviewed
t

2023-03-09 16:57 UTC, DeepVoyager253 reviewed
t

2023-03-09 16:57 UTC, DeepVoyager253 reviewed
t

2023-03-09 16:58 UTC, DeepVoyager253 reviewed
t

2023-03-09 16:58 UTC, DeepVoyager253 reviewed
t

2023-03-09 16:58 UTC, DeepVoyager253 reviewed
t

2023-03-09 16:59 UTC, DeepVoyager253 reviewed
v

2023-03-09 17:04 UTC, DeepVoyager253 reviewed
1

2023-03-09 17:05 UTC, DeepVoyager253 reviewed
111

2023-03-09 17:05 UTC, DeepVoyager253 reviewed
1

2023-03-09 17:11 UTC, Garulf commented
After choosing the "Download your video in full quailty" option I get this error:

```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\Garulf\AppData\Roaming\FlowLauncher\Logs\1.14.0\2023-03-09.txt
2. copy below exception message

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Garulf\AppData\Local\Programs\Python\Python311\pythonw.exe
Node Path: 
Date: 03/09/2023 12:11:06
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Garulf\AppData\Roaming\FlowLauncher\Plugins\YTDownloader\main.py", line 84, in <module>
    YoutubeDownload()
  File "C:\Users\Garulf\AppData\Roaming\FlowLauncher\Plugins\YTDownloader\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garulf\AppData\Roaming\FlowLauncher\Plugins\YTDownloader\main.py", line 46, in download_audio
    yt_video = pytube.YouTube(url)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garulf\AppData\Roaming\FlowLauncher\Plugins\YTDownloader\lib\pytube\__main__.py", line 71, in __init__
    self.video_id = extract.video_id(url)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garulf\AppData\Roaming\FlowLauncher\Plugins\YTDownloader\lib\pytube\extract.py", line 133, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garulf\AppData\Roaming\FlowLauncher\Plugins\YTDownloader\lib\pytube\helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass19_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 139
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ```

2023-03-09 17:18 UTC, Garulf commented on plugins.json
> +    "ExecuteFileName": "main.py",
```suggestion
```

2023-03-09 17:19 UTC, Garulf commented on plugins.json
> +    "ActionKeyword": "-yt",
```suggestion
```

2023-03-09 17:21 UTC, Garulf approved these changes

2023-03-09 17:22 UTC, merged