Add 7TV Emotes plugin
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #220
Opened 2023-03-11 11:11 UTC by WaterBoiledPizza

Made another plugin for searching emotes on 7tv. This project is based on the featured plugin [Garulf's BetterTTV-Twitch-Emotes](https://github.com/Garulf/BetterTTV-Twitch-Emotes)

2023-03-11 21:10 UTC, Garulf commented on plugins.json
> +        "LatestReleaseDate": "2023-03-11T18:53:00Z"
```suggestion
```

This will be added by the CI

2023-03-11 21:14 UTC, Garulf commented on plugins.json
> +        "UrlDownload": "https://github.com/WaterBoiledPizza/7TV-Emotes/releases/download/v0.0.1/Flow.Launcher.Plugin.7tvEmotes.zip",
```suggestion
        "UrlDownload": "https://github.com/WaterBoiledPizza/7TV-Emotes/releases/download/v0.0.1/Flow.Launcher.Plugin.7tvEmotes.zip"
```

Remove extra `,`.

2023-03-11 22:02 UTC, Garulf requested changes
Looks like the plugin raised an exception during the run test:

```

{"result": [{"Title": "TypeError", "SubTitle": "'NoneType' object is not subscriptable", "IcoPath": "C:\\Users\\runneradmin\\AppData\\Local\\FlowLauncher\\Images\\app_error.png", "ContextData": null, "Score": 0, "JsonRPCAction": {"method": "change_query", "parameters": [], "dontHideAfterAction": true}, "AutoCompleteText": "7tv TypeError"}, {"Title": "Report Issue", "SubTitle": "Report this issue to the developer", "IcoPath": "C:\\Users\\runneradmin\\AppData\\Local\\FlowLauncher\\Images\\browser.png", "ContextData": null, "Score": 0, "JsonRPCAction": {"method": "create_github_issue", "parameters": ["TypeError", "Traceback (most recent call last):%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\lib\\flox\\launcher.py\", line 44, in run%0A    results = request_method(*request_parameters) or self._results%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\lib\\flox\\__init__.py\", line 132, in _query%0A    self.query(query)%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\plugin\\main.py\", line 14, in query%0A    emotes = cache(seventv.trending_emotes)()%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\lib\\flox\\utils.py\", line 41, in wrapper%0A    data = func(*args, **kwargs)%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\plugin\\seventv.py\", line 65, in trending_emotes%0A    return _request(category=\"TRENDING_DAY\")%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\plugin\\seventv.py\", line 54, in _request%0A    data = data['data']['emotes']['items']%0ATypeError: 'NoneType' object is not subscriptable%0A"], "dontHideAfterAction": false}, "AutoCompleteText": "7tv Report Issue"}]}
```

Are you able to look into this?

2023-03-12 03:29 UTC, WaterBoiledPizza commented
> Looks like the plugin raised an exception during the run test:
> 
> ```
> 
> {"result": [{"Title": "TypeError", "SubTitle": "'NoneType' object is not subscriptable", "IcoPath": "C:\\Users\\runneradmin\\AppData\\Local\\FlowLauncher\\Images\\app_error.png", "ContextData": null, "Score": 0, "JsonRPCAction": {"method": "change_query", "parameters": [], "dontHideAfterAction": true}, "AutoCompleteText": "7tv TypeError"}, {"Title": "Report Issue", "SubTitle": "Report this issue to the developer", "IcoPath": "C:\\Users\\runneradmin\\AppData\\Local\\FlowLauncher\\Images\\browser.png", "ContextData": null, "Score": 0, "JsonRPCAction": {"method": "create_github_issue", "parameters": ["TypeError", "Traceback (most recent call last):%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\lib\\flox\\launcher.py\", line 44, in run%0A    results = request_method(*request_parameters) or self._results%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\lib\\flox\\__init__.py\", line 132, in _query%0A    self.query(query)%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\plugin\\main.py\", line 14, in query%0A    emotes = cache(seventv.trending_emotes)()%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\lib\\flox\\utils.py\", line 41, in wrapper%0A    data = func(*args, **kwargs)%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\plugin\\seventv.py\", line 65, in trending_emotes%0A    return _request(category=\"TRENDING_DAY\")%0A  File \"C:\\Users\\runneradmin\\AppData\\Roaming\\FlowLauncher\\Plugins\\7TV Emotes\\plugin\\seventv.py\", line 54, in _request%0A    data = data['data']['emotes']['items']%0ATypeError: 'NoneType' object is not subscriptable%0A"], "dontHideAfterAction": false}, "AutoCompleteText": "7tv Report Issue"}]}
> ```
> 
> Are you able to look into this?

what was the test input?

2023-03-12 03:33 UTC, WaterBoiledPizza commented
also where can i see the error logs when running the plugin? Is it plugin.log?

2023-03-12 04:06 UTC, Garulf commented
I see the issue. It's one I've struggled with myself. 

I'll elaborate once I'm at my computer again soon.

2023-03-12 04:17 UTC, Garulf commented
> what was the test input?

It's sent an empty query: `""`

> also where can i see the error logs when running the plugin? Is it plugin.log?

Yes it should output there.

2023-03-12 05:43 UTC, WaterBoiledPizza commented
> It's sent an empty query: `""`

I see the problem when i tried with the empty characters. Either way i can put a RegEX to filter out the excluded characters.

2023-03-12 05:53 UTC, Garulf commented
> > It's sent an empty query: `""`
> 
> I see the problem when i tried with the empty characters. Either way i can put a RegEX to filter out the excluded characters.

Okay. Feel free to update the PR with your latest release when you want.

2023-03-12 07:35 UTC, Garulf approved these changes

2023-03-12 07:36 UTC, merged