Added RemoveUSB
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #227
Opened 2023-04-19 20:20 UTC by jonasw234

Small plugin to detect removable USB devices and provide a query list to eject them safely.

2023-04-19 22:52 UTC, Garulf requested changes

2023-04-19 22:52 UTC, Garulf commented on plugins.json
> +        "UrlDownload": "https://github.com/jonasw234/FlowLauncher.Plugin.RemoveUSB/releases/download/1.0.0/FlowLauncher.Plugin.RemoveUSB.zip",
```suggestion
        "UrlDownload": "https://github.com/jonasw234/FlowLauncher.Plugin.RemoveUSB/releases/download/1.0.0/FlowLauncher.Plugin.RemoveUSB.zip"
```

2023-04-20 09:20 UTC, jonasw234 commented
I removed the superfluous comma from the `plugin.json` in the repo and the release as well (same as your edit). Is there anything else I need to do to re-run the tests?

2023-04-20 20:35 UTC, jonasw234 commented
Ah, my bad, I had the comma in the wrong line. Now it will hopefully work. Sorry for the mess.

2023-04-20 22:45 UTC, Garulf commented
Looks like the run test is failing because of a missing library. Please include all external libraries in your zip file. 

In this case it looks like the FlowLauncher library is missing.

2023-04-20 22:45 UTC, Garulf requested changes
Looks like the run test is failing because of a missing library. Please include all external libraries in your zip file. 

In this case it looks like the FlowLauncher library is missing.

2023-04-21 08:26 UTC, jonasw234 commented
Ah, I thought that FlowLauncher would be included automatically by your tests. Added it. Thanks for your patience :)

2023-04-21 14:48 UTC, Garulf commented
Please update the PR with the new version.

2023-04-21 14:57 UTC, jonasw234 commented
I added the Flow Launcher package to the `lib` folder like I in the plugin [isPrime](https://github.com/lvonkacsoh/Flow.Launcher.Plugin.IsPrime). Is anything else needed?

2023-04-21 16:37 UTC, Garulf commented
The test tries to emulate Flow Launcher using its built-in embedded Python which most users will probably be using. It will not see package directories like normal Python.

Please see here for more information: https://www.flowlauncher.com/docs/#/py-develop-plugins

2023-04-21 17:00 UTC, jonasw234 commented
I think I got it now. At least the workflow action worked and I added the additional lines in the documentation.

2023-04-22 16:56 UTC, Garulf commented on plugins.json
> +        "UrlDownload": "https://github.com/jonasw234/FlowLauncher.Plugin.RemoveUSB/releases/download/1.0.0/FlowLauncher.Plugin.RemoveUSB.zip"
```suggestion
        "UrlDownload": "https://github.com/jonasw234/FlowLauncher.Plugin.RemoveUSB/releases/download/v1.0.0/FlowLauncher.Plugin.RemoveUSB.zip"
```
Test is unable to find release download.
New versioning has "v" prepended

2023-04-22 18:18 UTC, Garulf commented
Looks like it passed the test! 🥳 

Looks like the test itself failed somehow though.

2023-04-22 18:18 UTC, Garulf approved these changes

2023-04-22 19:05 UTC, Garulf requested changes
Python 3.8 doesn't support `dict` usage as a type hint. In order to support the minimal version FLow Launcher supports please use `Dict` from the `typing` module on this line:

https://github.com/jonasw234/FlowLauncher.Plugin.RemoveUSB/blob/e3dca7a8e3410b054d5f74bf6ea8a8e19200bdaf/removeusb.py#L50

2023-04-22 20:30 UTC, jonasw234 commented
Ah, changed it, thanks!

2023-04-22 21:32 UTC, Garulf commented
I should've checked the rest of the code. Looks like you’re using `list` as well. Please use `List` the same as `Dict` earlier.

2023-04-24 08:32 UTC, jonasw234 commented
Okay, I just changed it, tested again with Python 3.8.10 and it seems to have worked. Fingers crossed.

2023-04-25 11:22 UTC, Garulf commented
It passed! (For real this time) 🥳

2023-04-25 11:23 UTC, Garulf approved these changes

2023-04-25 11:24 UTC, merged

2023-04-25 11:43 UTC, jonasw234 commented
Awesome! Thank you so much for your support, you’re amazing!