DeepFlow - plugin.json added
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #236
Opened 2023-05-11 16:57 UTC by DavidG33k

DeepL plugin to quickly translate with FlowLauncher.

2023-05-11 23:56 UTC, Garulf commented
Please provide the missing `UrlDownload` & `UrlSourceCode` fields.

2023-05-11 23:56 UTC, Garulf requested changes
Please provide the missing `UrlDownload` & `UrlSourceCode` fields.

2023-05-12 09:29 UTC, DavidG33k reviewed
Required info added in plugin.json and IcoPath value replaced with a statically.io CDN url.

2023-05-12 12:04 UTC, Garulf approved these changes

2023-05-12 12:05 UTC, merged