fix(discord): :bug: fix discord webhook failure when release notes too long (#250)
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #251
Opened 2023-06-06 04:40 UTC by JamesNZL

Fixes #250.

Currently, the release notes are added directly into a new embed field without checking its length.

If the release notes are longer than Discord's `1024` embed field value API limit, the webhook will fail to fire.
> This is pretty easily reached if you link issues/commits in your release notes, like semver tools often do:
  ![image](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/assets/44986932/fa05d6b0-2f55-4781-bd87-841149d481b5)

I've added a little formatting function that checks the length of the release notes and gracefully truncates if necessary (ie does its best to avoid markdown formatting errors by truncating entire lines, rather than half-way through a line).

Have unit tested the function.

![image](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/assets/44986932/64bc1461-3c04-4d28-8f5f-75dbf5161b53)

:)

2023-06-06 04:53 UTC, JamesNZL commented on ci/src/discord.py
> +    maximum_lines_message_length = len(release_notes)
Whoops, this is meant to be checking the number of digits of the length, ie
```py
len(str(len(release_notes)))
```

😅

2023-06-06 04:55 UTC, Garulf commented
Thanks! I'll take a closer look as soon as I can.

2023-06-06 04:57 UTC, JamesNZL commented on ci/src/discord.py
> +    maximum_lines_message_length = len(release_notes)
Though, I think this still works because of negative indices 🤔

2023-06-07 10:51 UTC, JamesNZL commented
Whoops, forgot to un-draft it yesterday.

Ready for review.

2023-06-11 02:03 UTC, Garulf requested changes

2023-06-11 02:03 UTC, Garulf commented on ci/src/discord.py
> +def truncate_release_notes(release_notes: str, length: int) -> str:
```suggestion
def truncate_release_notes(release_notes: str, length: int = MAX_BODY_LEN) -> str:
```
We should define "1024" as a constant so we don't use magic numbers. :)

2023-06-11 02:13 UTC, JamesNZL commented on ci/src/discord.py
> +    TRUNCATION_MESSAGE_BASE = "\n{} lines truncated..."
I like the 'show more' idea; it means less will be displayed in the embed itself but it's a lot more UX-friendly.

There *is* the link to the release in the embed title, but I think it is justifiable to use the characters to have a more semantic link in the event of truncation.

2023-06-11 02:16 UTC, JamesNZL commented on ci/src/discord.py
> +def truncate_release_notes(release_notes: str, length: int) -> str:
Yup good catch 😅, I think I let it slip cause I figured the surrounding logic was pretty tightly-coupled to the API anyway—will fix though

2023-06-11 02:34 UTC, Garulf commented on ci/src/discord.py
> +def truncate_release_notes(release_notes: str, length: int) -> str:
No problem. This doesn't affect the code as much but helps readability later.

2023-06-11 02:37 UTC, JamesNZL commented
Ready for re-review 🙂

2023-06-11 02:38 UTC, Garulf approved these changes

2023-06-11 02:39 UTC, merged