Update plugins.json
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #285
Opened 2023-09-20 14:35 UTC by DiekoMA

Added Godot plugin

2023-09-27 03:00 UTC, VictoriousRaptor submitted a review, later dismissed

2023-09-27 03:03 UTC, jjw24 requested changes
Minor changes

2023-09-27 03:05 UTC, jjw24 commented on plugins.json
> +        "LatestReleaseDate": "2023-09-20T14:33:01Z"
```suggestion
        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip"
```

2023-09-27 03:06 UTC, jjw24 commented on plugins.json
> +        "LatestReleaseDate": "2023-09-20T14:33:01Z"
DateAdded and LatestReleaseDate fields are auto-populated.

2023-09-27 03:09 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
I don't see a GitHub workflow file in your repo, are you uploading this zip by hand?

2023-09-27 10:55 UTC, DiekoMA commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
yes

2023-09-27 11:03 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
Could we ask you to use GitHub Actions to publish your plugin please. The reason is packaging and uploading the zip manually is hard for us to make reasonable judgement that what's contained in the zip is the same from the repository.

You can follow this as the example, most likely just need to replace the dotnet version and the name of the plugin: https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml

2023-09-28 16:56 UTC, DiekoMA commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
sure thing

2023-09-28 23:24 UTC, DiekoMA commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
i've set up the workflow

2023-09-28 23:57 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
Hmm for some reason you are getting 403 on publish, something to do with the token you defined in the workflow maybe - https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/blob/5f7f7dcbc6fe9fbf9e768351cc18f69385ea379b/.github/workflows/main.yml#L37

Maybe try setting your own token perhaps.

2023-09-28 23:59 UTC, DiekoMA commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
I can use a personal access token with permissions for actions right ?

2023-09-29 00:07 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
Yep

2023-09-29 00:20 UTC, DiekoMA commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
still didn't run, it also said i can't name a secret GITHUB_TOKEN

2023-10-01 00:02 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
Change the secret name from GITHUB_TOKEN to a different one, must be the same as the token name you added in the GitHub settings page

2023-10-02 19:59 UTC, DiekoMA commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
It's working properly now, thank you

2023-10-03 19:10 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip",
No worries, thanks for fixing it up. Will take a look later when in front of computer.

2023-10-04 09:42 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/tag/v1.0.0/Godot.zip"
```suggestion
        "Author": "DiekoMA",
        "Version": "1.0.1",
        "Language": "csharp",
        "Website": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot",
        "IcoPath": "https://cdn.jsdelivr.net/gh/DiekoMA/Flow.Launcher.Plugin.Godot@master/Assets/Godot.png",
        "UrlSourceCode": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/tree/master",
        "UrlDownload": "https://github.com/DiekoMA/Flow.Launcher.Plugin.Godot/releases/download/v1.0.1/Godot-1.0.1.zip"
```

2023-10-04 09:42 UTC, jjw24 approved these changes

2023-10-04 09:44 UTC, merged