Added RDP Plugin
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #292
Opened 2023-10-06 10:42 UTC by MBeggiato

Proposed to add the [RDP Plugin](https://github.com/MBeggiato/Flow.Launcher.Plugin.RDP) to the official list. <br>
![](https://cdn.jsdelivr.net/gh/MBeggiato/Flow.Launcher.Plugin.RDP@main/show.gif)

2023-10-06 13:31 UTC, MBeggiato commented
Fixed: ERROR ci/src/validator.py - json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1947 column 6 (char 104045)
With [this](https://github.com/MBeggiato/Flow.Launcher.PluginsManifest/commit/1342c81d13fc2206d2ef4ce92a3383bc83b7103f)

2023-10-06 14:37 UTC, VictoriousRaptor commented
And please make the indentation consistent.

2023-10-08 12:08 UTC, MBeggiato commented
> And please make the indentation consistent.

Done with [this](https://github.com/MBeggiato/Flow.Launcher.PluginsManifest/commit/f4ed04c2b953ed06f8e8dd5eb8025121d767c54d).
Thanks for the tip!

2023-10-08 16:49 UTC, MBeggiato commented
The last issue is not related to my pr right?

2023-10-08 23:45 UTC, VictoriousRaptor commented
> The last issue is not related to my pr right?

looks like you don't have that image/logo.png in your repo.

2023-10-09 02:36 UTC, jjw24 requested changes

2023-10-09 02:36 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/MBeggiato/Flow.Launcher.Plugin.RDP/releases/download/v1.0.0.12/Flow.Launcher.Plugin.RDP.zip",
There is a mismatch between the version indicated and in your download link.

Could you also use Semantic Versioning in the form of X.Y.Z please.

2023-10-09 07:24 UTC, MBeggiato commented on plugins.json
> +        "UrlDownload": "https://github.com/MBeggiato/Flow.Launcher.Plugin.RDP/releases/download/v1.0.0.12/Flow.Launcher.Plugin.RDP.zip",
I see! I fixed the version to match the form X.Y.Z. The latest release is now 1.0.13, just like in the plugin.json

2023-10-09 09:04 UTC, jjw24 commented on plugins.json
> +        "UrlDownload": "https://github.com/MBeggiato/Flow.Launcher.Plugin.RDP/releases/download/v1.0.0.12/Flow.Launcher.Plugin.RDP.zip",
A could of additional changes please:
1. The 'Version' field need to match the version used in the 'UrlDownload' field, see above.
2. Most importantly could we ask you to use GitHub Actions to publish your plugin please. The reason is packaging and uploading the zip manually is hard for us to make reasonable judgement that what's contained in the zip is the same from the repository.

You can follow this as the example, most likely just need to replace the dotnet version and the name of the plugin: https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml

2023-10-16 11:09 UTC, MBeggiato commented on plugins.json
> +        "UrlDownload": "https://github.com/MBeggiato/Flow.Launcher.Plugin.RDP/releases/download/v1.0.0.12/Flow.Launcher.Plugin.RDP.zip",
@jjw24 Thanks for the requested changes. I think I finaly got it all working. Had a bit of trouble with Github Actions but now it should work!

2023-10-23 03:44 UTC, VictoriousRaptor approved these changes

2023-10-23 03:45 UTC, merged