Add Laravel Docs Plugin
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #295
Opened 2023-11-07 18:58 UTC by Henriquex25

A simple plugin to search and access Laravel documentation

[Repository](https://github.com/Henriquex25/laravel-doc-flow-launcher-plugin)

2023-11-12 04:18 UTC, jjw24 commented on plugins.json
> +        "LatestReleaseDate": "2023-11-07T06:56:46Z"
```suggestion
        "IcoPath": "https://cdn.jsdelivr.net/gh/Henriquex25/laravel-doc-flow-launcher-plugin@main/assets/laravel.png"
```

2023-11-12 04:19 UTC, jjw24 commented
No need to add `DateAdded` and `LatestReleaseDate` fields, they will be auto populated. I updated the icon url to use mirror link.

2023-11-12 04:35 UTC, jjw24 requested changes
Hey the executable path does not exist: ./dist/main.js
Do you mean ./src/main.ts in the plugin.json file?

Plugin currently failing to load with the latest release.

2023-11-12 15:25 UTC, Henriquex25 commented
> Hey the executable path does not exist: ./dist/main.js Do you mean ./src/main.ts in the plugin.json file?
> 
> Plugin currently failing to load with the latest release.

I used the [flow-launcher-plugin-template-node](https://github.com/Joehoel/flow-launcher-plugin-template-node) repository as a base.

the javascript file is being built in the path ./dist/main.js

2023-11-14 09:59 UTC, jjw24 commented
At the moment flow is not able to find the executable file indicated in plugin.json. let me know once you have sorted this issue I will re-test

2024-02-04 06:09 UTC, jjw24 commented
> > Hey the executable path does not exist: ./dist/main.js Do you mean ./src/main.ts in the plugin.json file?
> > Plugin currently failing to load with the latest release.
> 
> I used the [flow-launcher-plugin-template-node](https://github.com/Joehoel/flow-launcher-plugin-template-node) repository as a base.
> 
> the javascript file is being built in the path ./dist/main.js

the downloaded plugin zip does not contain  ./dist/main.js

2024-02-05 00:34 UTC, taooceros commented
let's wait #319

2024-02-05 02:25 UTC, jjw24 commented
The issue here is not related to that PR though

2024-03-27 11:54 UTC, jjw24 commented
Closing, please resubmit when ready.

2024-03-27 11:54 UTC, closed without merging