add RollDice plugin entry
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #45
Opened 2021-04-21 19:08 UTC by lvonkacsoh

I had fun porting the isPrime plugin, so I made a new plugin to roll some dice 😄 
Please hit me up if something's amiss.

2021-04-21 21:19 UTC, jjw24 commented on plugins.json
> +        "ExecuteFileName": "main.py",
could you remove this attribute please, not needed.

once this plugin is added don't forget to update the readme as it says yet to be added to flow

2021-04-22 05:31 UTC, lvonkacsoh commented on plugins.json
> +        "ExecuteFileName": "main.py",
You're right, I totally overlooked this attribute.
I updated the isPrime readme yesterday because I forgot to change exactly that there as well. 😅

2021-04-22 07:09 UTC, jjw24 commented on plugins.json
> +        "ExecuteFileName": "main.py",
Can you also remove icopath attribute for both isPrime and RollDice please

2021-04-22 08:13 UTC, taooceros requested changes

2021-04-22 08:13 UTC, taooceros commented on plugins.json
>          "IcoPath": "assets\\icon.png",
```suggestion
```

2021-04-22 08:13 UTC, taooceros commented on plugins.json
> +        "IcoPath": "assets\\icon.jpg",
```suggestion
```

2021-04-22 13:00 UTC, jjw24 commented
@taooceros if you got 2 secs could you help resolve the conflict, I am afk, other wise will do it tomorrow

2021-04-22 13:05 UTC, taooceros commented
> @taooceros if you got 2 secs could you help resolve the conflict, I am afk, other wise will do it tomorrow

Sorry, I am also afk now😂😂😂 Let's do it tomorrow.

2021-04-22 15:04 UTC, lvonkacsoh commented on plugins.json
> +        "ExecuteFileName": "main.py",
Done :)

2021-04-22 22:59 UTC, jjw24 approved these changes

2021-04-22 23:00 UTC, merged

2021-04-22 23:01 UTC, jjw24 commented
Merged. Thank you :)