CI: hourly update -> daily update
Flow-Launcher/Flow.Launcher.PluginsManifest pull request #56
Opened 2021-07-15 03:03 UTC by Zeroto521

https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/actions/workflows/updater.yaml

Hourly update upstream is too frequent.
Let us change to a daily update.

2021-07-15 03:05 UTC, taooceros approved these changes

2021-07-15 03:10 UTC, jjw24 requested changes
Maybe every 3 hrs instead? Daily means plugin fix is updated in their repo but the users won't be able to download until next day, I think it's too long. 

Also need to update readme as well to reflect this change

2021-07-15 03:35 UTC, jjw24 commented
Just need to update this line in the readme:
```
Our CI will automatically check for new updates from plugins at every hour and update to the newer version if they are stored in the Github Release. 
```

2021-07-16 11:32 UTC, jjw24 approved these changes

2021-07-16 11:33 UTC, merged